wf_basedir = workflow.current_basedir


rule target:
    input:
        fasta_ref=expand("results/01_fasta_ref/{reference_name}.all.fasta.gz", reference_name=config["reference_name"]),


rule create_fasta_reference:
    input:
        graph_file=config["graph"],
        validation_file="results/00_validate_inputs/{reference_name}.graph_validation.txt"
    output:
        fasta_ref="results/01_fasta_ref/{reference_name}.all.fasta.gz",
        # These won't be used, but we need to make sure they are created
        fasta_index_bwt="results/01_fasta_ref/{reference_name}.all.fasta.gz.bwt",
        fasta_index_sa="results/01_fasta_ref/{reference_name}.all.fasta.gz.sa",
        fasta_index_pac="results/01_fasta_ref/{reference_name}.all.fasta.gz.pac",
        fasta_index_ann="results/01_fasta_ref/{reference_name}.all.fasta.gz.ann",
        fasta_index_amb="results/01_fasta_ref/{reference_name}.all.fasta.gz.amb"
    conda:
        "../envs/main.yaml"
    shell:
        """
        # Create the fasta reference file from the graph
        odgi paths -i {input.graph_file}  --fasta | gzip > {output.fasta_ref}
        # Create bwa index
        bwa index {output.fasta_ref}
        """

