wildcard_constraints:
    reference_name=config["reference_name"]
#    mode=config["threshold_mode"]

rule target:
    input:
        kinship_matrix=expand("results/04_kinship/{reference_name}.kinship", reference_name=config["reference_name"]),

rule copy_kinship_matrix:
    input:
        source_kinship_matrix=config["kinship_matrix"],
    output:
        kinship_matrix="results/04_kinship/{reference_name}.kinship"
    shell:
        "cp {input.source_kinship_matrix} {output.kinship_matrix}"
