# General configuration for all modules
samples: "config/samples.csv"
phenotypes: "config/phenotypes.csv"
graph: "testdata/graphs/2155413.gfa"
reference_name: "1001g_plus_pan"
pan_sn_delimiter: "#"

# 01 - Prepare reference genome
# Nothing to set (yet)

# 02 - make pack files
use_fasta_ref: true


# 03 - make fambedbims
threshold_mode: "p0.1"


# 04 - make kinship
kinship_method: "file"
use_snp_kinship: false
use_graph_kinship: false
kinship_matrix: "kinship_matrix.kinship"


# 05 - gwas
# Nothing to set (yet)