$schema: "https://json-schema.org/draft-06/schema#"
type: object
required:
  - samples
  - phenotypes
  - graph
  - reference_name
  - normalization_method
  - normalization_method_fraction
properties:
  samples:
    type: string
    description: "Path to the samples file."
  phenotypes:
    type: array
    minItems: 1
    items:
      type: object
      minProperties: 1
      maxProperties: 1
      additionalProperties: false
      patternProperties:
        "^[a-zA-Z0-9_]+$":
          type: string
          description: "Path to the phenotype file for this phenotype."
  graph:
    type: string
    description: "Path to the GFA file for the graph."
  reference_name:
    type: string
    description: "Reference name used in the configuration."
  pan_sn_delimiter:
    type: string
    maxLength: 1
    default: "#"
    description: "Single character used as the delimiter for pan-sn."
  use_fasta_ref:
    type: boolean
    default: true
    description: "Flag to indicate if FASTA reference is used."
  normalization_method:
    type: string
    enum:
      - percentile
      - other_method
    description: "Method for normalization (e.g., percentile)."
  normalization_method_fraction:
    type: string
    pattern: "^(0(\\.\\d+)?|1(\\.0+)?)$"
    description: "Fraction for normalization, as a string between '0' and '1'."
  gfa2bin:
    type: string
    default: ""
    description: "Path to the gfa2bin tool."
  kinship_method:
    type: string
    enum:
      - file
      - other_method
    default: "file"
    description: "Method used for kinship calculation."
  kinship_matrix:
    type: string
    default: ""
    description: "Path to the kinship matrix file."
